# This is a basic workflow that is manually triggered

name: Patch new version

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: quickjs-universal
    - name: Patch
      run: |
        pushd quickjs-universal
        pwsh ./Patch.ps1
        popd
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        path: quickjs-universal
        add-paths: PatchedSources/
