# This is a basic workflow that is manually triggered

name: Patch new version

on:
  workflow_dispatch:

jobs:
  create-patch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: quickjs-universal

    - name: Patch
      id: patch
      run: |
        pushd quickjs-universal
        pwsh ./Patch.ps1
        pushd OriginalSources/
        commitHash=$(git rev-parse --short HEAD)
        popd
        echo "commitHash=$commitHash" >> "$GITHUB_OUTPUT"
        popd
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        path: quickjs-universal
        add-paths: PatchedSources/
        branch: ${{ format('patch/{0}', steps.patch.outputs.commitHash) }}
